version: 2.1

orbs:
  maven: circleci/maven@1.1.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
executors:
  my_executor:
    docker:
      - image: 'cimg/openjdk:<<parameters.tag>>'
    parameters:
      tag:
        default: "15.0"
        type: string
