version: 2.1

orbs:
  maven: circleci/maven@1.2.0

executors:
  my-executor:
    docker:
      - image: cimg/openjdk:15.0.1

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          executor: my-executor
parameters:
  verify_dependencies:
    default: false
    type: boolean
