version: 2.1

orbs:
  maven: circleci/maven@1.1.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
parameters:
  tag:
    type: string
    default: "15.0"
